### ISSUE TITLE
suggestion: output all plots, their full path and their "type" to a delimited file for post-processing

### ISSUE THREAD

**Issue by x-vibe** [uchiafarmer/chia-tools#3]
Hi again, not a bug, just an idea: do you think there would be merit in piping an output of the analysis to a text file that one could use in Excel? I am thinking if people have 1000 plots and they are all in different sub folders (i.e. JBOD setup), then moving these files to different folders would be quite tedious (not to mention from subdirectories).

However, if you had a text file, people could decide themselves how to process that data. I was thinking along the lines of  the below..

OG | /mnt/disk1/plots/plot-k32-.....plot
NFT |  /mnt/disk12/plots/plot-k32-.....plot 

What do you think? Not too different from what you are already outputting anyway, with the "OG plot found:" line.. Happy to help test and debug and worst case, one could just pipe your existing output to a text file anyhow, so maybe more of a gimmick...

**Comment by uchiafarmer** [comment]
I was thinking of doing something similar. I'll look into it. Shouldnt be too difficult.

**Comment by uchiafarmer** [comment]
Feature added with [ec59b7b](https://github.com/uchiafarmer/chia-tools/commit/ec59b7b7fb1fb1ab3f637ffe89cda73bbb72334e#diff-24abbb2d31f3c270fd25d666226815c98b13ad3b6baaecd9e51951da7b52721e)

Use `-o <FILE>` to create a CSV file of discovered plots.
If the file exists it will be overwritten. It will be up to the user to manage their output files.
The CSV file can then be imported or opened by a spreadsheet application to view plots.
